steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - asia-south1-docker.pkg.dev/kp3p-admin-prod/kp3p-repo/kp3p-admin:$COMMIT_SHA
      - -t
      - asia-south1-docker.pkg.dev/kp3p-admin-prod/kp3p-repo/kp3p-admin:latest
      - .

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - --all-tags
      - asia-south1-docker.pkg.dev/kp3p-admin-prod/kp3p-repo/kp3p-admin

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - kp3p-admin
      - --image=asia-south1-docker.pkg.dev/kp3p-admin-prod/kp3p-repo/kp3p-admin:$COMMIT_SHA
      - --region=asia-south1
      - --project=kp3p-admin-prod
      - --quiet

options:
  logging: CLOUD_LOGGING_ONLY

images:
  - asia-south1-docker.pkg.dev/kp3p-admin-prod/kp3p-repo/kp3p-admin:$COMMIT_SHA
  - asia-south1-docker.pkg.dev/kp3p-admin-prod/kp3p-repo/kp3p-admin:latest
